### ISSUE TITLE
regression: decl literals arent resolved

### ISSUE THREAD

**Issue by xdBronch** [zigtools/zls#2235]
### Zig Version

0.15.0-dev.155+acfdad858

### ZLS Version

0.15.0-dev.17+b30d4de3

### Steps to Reproduce and Observed Behavior

caused by #2133. decl literals no longer get completions, hover, goto def, etc at all

### Expected Behavior

work !

### Relevant log output

```shell

```

**Comment by Techatrix** [comment]
Decl literals do still work generally since they are covered by tests so please provide reproducible steps. Decls literals on types like `std.ArrayListUnmanaged` have regressed however which has been fixed by c105a373de50b116ca9eaa1e62075c343e276365. I am going to assume that this issue has encountered this.

**Comment by xdBronch** [comment]
that is a very good point about tests... and yeah, thats exactly where i hit it. apologies for not being descriptive, i thought i had tested other cases but i guess not. 
that commit has seemed to fix completions but im still not getting hover or goto definition
```zig
const std = @import("std");
pub fn main() !void {
    const list: std.ArrayListUnmanaged(u8) = .empty;
    _ = list;
}
```

**Comment by Techatrix** [comment]
> that commit has seemed to fix completions but im still not getting hover or goto definition

Thanks for noticing. This should be fixed by 7e8671afc26e5740ffd8265edd69fc2c5a4c3895 and bcc5d9fd67d815613cce0294a0d45b0d76cecd88.
